apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: module-deployment
  spec:
    selector:
      matchLabels:
        app: module
    replicas: 1
    template:
      metadata:
        labels:
          app: module
      spec:
        containers:
        - name: module
          image: vod-module
          imagePullPolicy: Never
          ports:
          - containerPort: 31000
          volumeMounts:
          - name: nfsvol-3
            mountPath: /opt/static/videos
          volumeMounts:
          - name: module-config
            mountPath: /etc/nginx/conf.d/vod_module.conf
            subPath: vod_module.conf
        volumes:
        - name: nfsvol-3
          persistentVolumeClaim:
            claimName: nfs-pvc
        - name: module-config
          configMap:
            name: module-config
- apiVersion: v1
  kind: Service
  metadata:
    name: module
  spec:
    selector:
      app: module
    type: NodePort
    ports:
    - name: module
      protocol: TCP
      port: 31000
      nodePort: 31000
      targetPort: 31000
