apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vod-webapi-deployment
    labels:
      app: vod-webapi
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: vod-webapi
    template:
      metadata:
        labels:
          app: vod-webapi
      spec:
        containers:
        - name: vod-webapi
          image: vod-webapi
          imagePullPolicy: Never
          volumeMounts:
          - name: nfsvol
            mountPath: ./videos
          env:
          - name: MONGO_URL
            value: mongodb
          - name: MONGO_PORT
            value: "27017"
          - name: RABBIT_HOST
            value: rabbit
          - name: RABBIT_PORT
            value: "5672"
          - name: BASE_URL
            value: "vod.thanaphat.me:30000"
          - name: BASE_VIDEOS_FOLDER
            value: "./videos"
          ports:
          - containerPort: 5000
        volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: nfs-pvc
- apiVersion: v1
  kind: Service
  metadata:
    name: vod-webapi
  spec:
    selector:
      app: vod-webapi
    ports:
    - name: vod-webapi
      protocol: TCP
      port: 5000
      targetPort: 5000
