apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vod-frontend-deployment
    labels:
      app: vod-frontend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: vod-frontend
    template:
      metadata:
        labels:
          app: vod-frontend
      spec:
        containers:
        - name: vod-frontend
          image: vod-frontend
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: vod-frontend
  spec:
    selector:
      app: vod-frontend
    type: NodePort
    ports:
    - name: vod-frontend
      protocol: TCP
      port: 8080
      targetPort: 8080
