apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vod_module-deployment
  spec:
    selector:
      matchLabels:
        app: vod_module
    replicas: 1
    template:
      metadata:
        labels:
          app: vod_module
      spec:
        containers:
        - name: vod_module
          image: vod_module
          ports:
          - containerPort: 4000
          volumeMounts:
          - name: vod-module-config
            mountPath: /etc/nginx/conf.d/vod_module.conf
            subPath: vod_module.conf
        volumes:
          - name: vod-module-config
            configMap:
              name: vod-module-config
- apiVersion: v1
  kind: Service
  metadata:
    name: vod_module
  spec:
    selector:
      app: vod_module
    type: NodePort
    ports:
    - name: vod_module
      protocol: TCP
      port: 4000
      nodePort: 4000
      targetPort: 4000
