apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vod-converter-deployment
    labels:
      app: vod-converter
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: vod-converter
    template:
      metadata:
        labels:
          app: vod-converter
      spec:
        containers:
        - name: vod-converter
          image: vod-converter
          imagePullPolicy: Never
          env:
          - name: MONGO_URL
            value: mongodb
          - name: MONGO_PORT
            value: "27017"
          - name: RABBIT_HOST
            value: rabbit
          - name: RABBIT_PORT
            value: "5672"
