apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vod-like-worker-deployment
    labels:
      app: vod-like-worker
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: vod-like-worker
    template:
      metadata:
        labels:
          app: vod-like-worker
      spec:
        containers:
        - name: vod-like-worker
          image: tui95/vod-like-worker
          imagePullPolicy: Always
          env:
          - name: MONGO_URL
            value: mongodb
          - name: MONGO_PORT
            value: "27017"
          - name: RABBIT_HOST
            value: rabbit
          - name: RABBIT_PORT
            value: "5672"
